modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

issueTrackerURL="https://github.com/MarbledHubb-Studios/Repair-My-Anvil/issues"

[[mods]]
modId="repair_my_anvil"
version="1.1.0.0"
displayName="Repair My Anvil!"
displayURL="https://marbledhubb.com/projects/mods/repair-my-anvil"
logoFile="rpa_icon_static.png"
credits="MarbledHubb Studios"
authors="MarbledNull, WereF0X, Aimiwi"

description='''A mod that adds a simple repairing mechanic to Anvils.'''

[[dependencies.repair_my_anvil]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.repair_my_anvil]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
